version: "3"
services:
    pihole:
        container_name: pihole
        image: pihole/pihole:latest
        ports:
            - "53:53/tcp"
            - "53:53/udp"
            - "67:67/udp"
            - "80:80/tcp"
            - "4433:443/tcp"
        environment:
            - TZ=Europe/Rome
            - WEBPASSWORD=changeme
        volumes:
            - "./pihole/etc-pihole/:/etc/pihole/"
            - "./pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/"
        dns:
            - 127.0.0.1
            - 1.1.1.1
        cap_add:
            - NET_ADMIN
        restart: unless-stopped

    transmission:
        image: linuxserver/transmission
        container_name: transmission
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/Rome
            - TRANSMISSION_WEB_HOME=/combustion-release/
            - USER=simone
            - PASS=changeme
        volumes:
            - ./transmission/config:/config
            - ./transmission/downloads/:/downloads
            - ./transmission/watch folder:/watch
        ports:
            - 9091:9091
            - 9999:51413
            - 9999:51413/udp
        restart: unless-stopped

    portainer:
        image: portainer/portainer
        container_name: portainer
        command: -H unix:///var/run/docker.sock
        restart: always
        ports:
            - 9000:9000
            - 8000:8000
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - portainer_data:/data
volumes:
    portainer_data: